In [4]:
pip install intake-esm xarray gcsfs netCDF4 zarr

Collecting intake-esmNote: you may need to restart the kernel to use updated packages.

  Downloading intake_esm-2025.12.12-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: xarray in c:\users\12094\anaconda3\lib\site-packages (2026.4.0)
Requirement already satisfied: gcsfs in c:\users\12094\anaconda3\lib\site-packages (2026.5.0)
Collecting netCDF4
  Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: zarr in c:\users\12094\anaconda3\lib\site-packages (3.2.1)
Requirement already satisfied: dask>=2024.12 in c:\users\12094\anaconda3\lib\site-packages (from dask[complete]>=2024.12->intake-esm) (2025.2.0)
Collecting fastprogress>=1.0.0 (from intake-esm)
  Downloading fastprogress-1.1.6-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: fsspec>=2024.12 in c:\users\12094\anaconda3\lib\site-packages (from intake-esm) (2026.3.0)
Requirement already satisfied: intake>=2.0.0 in c:\users\12094\anaconda3\lib\site-packages (from intake-esm) (2.0.7)
Collecting itables (from intake-esm)
  Downloading itables-2.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas>=2.1.0 in c:\users\12094\anaconda3\lib\site-packages (from intake-esm) (2.2.3)
Collecting polars<1.33.0,>=1.24.0 (from intake-esm)
  Downloading polars-1.32.3-cp39-abi3-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: pydantic>=2.0 in c:\users\12094\anaconda3\lib\site-packages (from intake-esm) (2.10.3)
Collecting pydap!=3.5.5 (from intake-esm)
  Downloading pydap-3.5.9-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: requests>=2.24.0 in c:\users\12094\anaconda3\lib\site-packages (from intake-esm) (2.32.3)
Collecting kerchunk>=0.2.9 (from intake-esm)
  Downloading kerchunk-0.2.10-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: numpy>=1.26 in c:\users\12094\anaconda3\lib\site-packages (from xarray) (2.1.3)
Requirement already satisfied: packaging>=24.2 in c:\users\12094\anaconda3\lib\site-packages (from xarray) (24.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (3.11.10)
Requirement already satisfied: decorator>4.1.2 in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (5.1.1)
Requirement already satisfied: google-auth-oauthlib in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (1.4.0)
Requirement already satisfied: google-auth>=1.2 in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (2.53.0)
Requirement already satisfied: google-cloud-storage-control in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (1.11.0)
Requirement already satisfied: google-cloud-storage>=3.9.0 in c:\users\12094\anaconda3\lib\site-packages (from gcsfs) (3.10.1)
Requirement already satisfied: cftime in c:\users\12094\anaconda3\lib\site-packages (from netCDF4) (1.6.5)
Requirement already satisfied: certifi in c:\users\12094\anaconda3\lib\site-packages (from netCDF4) (2025.4.26)
Requirement already satisfied: donfig>=0.8 in c:\users\12094\anaconda3\lib\site-packages (from zarr) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in c:\users\12094\anaconda3\lib\site-packages (from zarr) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in c:\users\12094\anaconda3\lib\site-packages (from zarr) (0.16.5)
Requirement already satisfied: typing-extensions>=4.13 in c:\users\12094\anaconda3\lib\site-packages (from zarr) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\12094\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.18.0)
Requirement already satisfied: idna>=2.0 in c:\users\12094\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (3.7)
Requirement already satisfied: click>=8.1 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (8.1.8)
Requirement already satisfied: cloudpickle>=3.0.0 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (3.0.0)
Requirement already satisfied: partd>=1.4.0 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (1.0.0)
Requirement already satisfied: colorama in c:\users\12094\anaconda3\lib\site-packages (from click>=8.1->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (0.4.6)
Requirement already satisfied: pyarrow>=14.0.1 in c:\users\12094\anaconda3\lib\site-packages (from dask[complete]>=2024.12->intake-esm) (19.0.0)
Requirement already satisfied: lz4>=4.3.2 in c:\users\12094\anaconda3\lib\site-packages (from dask[complete]>=2024.12->intake-esm) (4.3.2)
Collecting fastcore>=1.10.0 (from fastprogress>=1.0.0->intake-esm)
  Downloading fastcore-1.13.2-py3-none-any.whl.metadata (3.4 kB)
Collecting python-fasthtml>=0.12.34 (from fastprogress>=1.0.0->intake-esm)
  Downloading python_fasthtml-0.14.1-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\12094\anaconda3\lib\site-packages (from google-auth>=1.2->gcsfs) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\12094\anaconda3\lib\site-packages (from google-auth>=1.2->gcsfs) (44.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\12094\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=1.2->gcsfs) (1.17.1)
Requirement already satisfied: pycparser in c:\users\12094\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=1.2->gcsfs) (2.21)
Requirement already satisfied: google-api-core<3.0.0,>=2.27.0 in c:\users\12094\anaconda3\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.30.3)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.2 in c:\users\12094\anaconda3\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in c:\users\12094\anaconda3\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.9.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\12094\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage>=3.9.0->gcsfs) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in c:\users\12094\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage>=3.9.0->gcsfs) (6.33.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in c:\users\12094\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage>=3.9.0->gcsfs) (1.28.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\12094\anaconda3\lib\site-packages (from requests>=2.24.0->intake-esm) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\12094\anaconda3\lib\site-packages (from requests>=2.24.0->intake-esm) (2.3.0)
Requirement already satisfied: platformdirs in c:\users\12094\anaconda3\lib\site-packages (from intake>=2.0.0->intake-esm) (4.3.7)
Requirement already satisfied: networkx in c:\users\12094\anaconda3\lib\site-packages (from intake>=2.0.0->intake-esm) (3.4.2)
Requirement already satisfied: ujson in c:\users\12094\anaconda3\lib\site-packages (from kerchunk>=0.2.9->intake-esm) (5.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\12094\anaconda3\lib\site-packages (from pandas>=2.1.0->intake-esm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\12094\anaconda3\lib\site-packages (from pandas>=2.1.0->intake-esm) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\12094\anaconda3\lib\site-packages (from pandas>=2.1.0->intake-esm) (2025.2)
Requirement already satisfied: locket in c:\users\12094\anaconda3\lib\site-packages (from partd>=1.4.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (1.0.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\12094\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.4.8)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\12094\anaconda3\lib\site-packages (from pydantic>=2.0->intake-esm) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\12094\anaconda3\lib\site-packages (from pydantic>=2.0->intake-esm) (2.27.1)
Collecting requests-cache (from pydap!=3.5.5->intake-esm)
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: scipy in c:\users\12094\anaconda3\lib\site-packages (from pydap!=3.5.5->intake-esm) (1.15.3)
Collecting Webob (from pydap!=3.5.5->intake-esm)
  Downloading WebOb-1.8.9-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\12094\anaconda3\lib\site-packages (from pydap!=3.5.5->intake-esm) (4.12.3)
Requirement already satisfied: lxml in c:\users\12094\anaconda3\lib\site-packages (from pydap!=3.5.5->intake-esm) (5.3.0)
Requirement already satisfied: Jinja2 in c:\users\12094\anaconda3\lib\site-packages (from pydap!=3.5.5->intake-esm) (3.1.6)
Requirement already satisfied: six>=1.5 in c:\users\12094\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->intake-esm) (1.17.0)
Collecting starlette~=1.0 (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading starlette-1.0.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: oauthlib in c:\users\12094\anaconda3\lib\site-packages (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (3.3.1)
Requirement already satisfied: itsdangerous in c:\users\12094\anaconda3\lib\site-packages (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (2.2.0)
Collecting uvicorn>=0.30 (from uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading uvicorn-0.47.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: httpx in c:\users\12094\anaconda3\lib\site-packages (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (0.28.1)
Collecting fastlite>=0.1.1 (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading fastlite-0.2.4-py3-none-any.whl.metadata (12 kB)
Collecting python-multipart (from python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading python_multipart-0.0.29-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\12094\anaconda3\lib\site-packages (from starlette~=1.0->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (4.7.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\12094\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette~=1.0->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (1.3.0)
Collecting apswutils>=0.1.2 (from fastlite>=0.1.1->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading apswutils-0.1.2-py3-none-any.whl.metadata (9.1 kB)
Collecting apsw (from apswutils>=0.1.2->fastlite>=0.1.1->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading apsw-3.53.1.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: h11>=0.8 in c:\users\12094\anaconda3\lib\site-packages (from uvicorn>=0.30->uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (0.16.0)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading httptools-0.7.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\12094\anaconda3\lib\site-packages (from uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (1.1.0)
Collecting watchfiles>=0.20 (from uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading watchfiles-1.2.0-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.30->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\12094\anaconda3\lib\site-packages (from beautifulsoup4->pydap!=3.5.5->intake-esm) (2.5)
Requirement already satisfied: distributed==2025.2.0 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (2025.2.0)
Requirement already satisfied: bokeh>=3.1.0 in c:\users\12094\anaconda3\lib\site-packages (from dask>=2024.12->dask[complete]>=2024.12->intake-esm) (3.6.2)
Requirement already satisfied: msgpack>=1.0.2 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (1.0.3)
Requirement already satisfied: psutil>=5.8.0 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (5.9.0)
Requirement already satisfied: sortedcontainers>=2.0.5 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (3.1.0)
Requirement already satisfied: tornado>=6.2.0 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (6.5.1)
Requirement already satisfied: zict>=3.0.0 in c:\users\12094\anaconda3\lib\site-packages (from distributed==2025.2.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (3.0.0)
Requirement already satisfied: contourpy>=1.2 in c:\users\12094\anaconda3\lib\site-packages (from bokeh>=3.1.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (1.3.1)
Requirement already satisfied: pillow>=7.1.0 in c:\users\12094\anaconda3\lib\site-packages (from bokeh>=3.1.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (11.1.0)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\users\12094\anaconda3\lib\site-packages (from bokeh>=3.1.0->dask>=2024.12->dask[complete]>=2024.12->intake-esm) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\12094\anaconda3\lib\site-packages (from Jinja2->pydap!=3.5.5->intake-esm) (3.0.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\12094\anaconda3\lib\site-packages (from google-auth-oauthlib->gcsfs) (2.0.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\12094\anaconda3\lib\site-packages (from google-cloud-storage-control->gcsfs) (1.80.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in c:\users\12094\anaconda3\lib\site-packages (from google-cloud-storage-control->gcsfs) (0.14.4)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in c:\users\12094\anaconda3\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-storage-control->gcsfs) (1.80.0)
Requirement already satisfied: httpcore==1.* in c:\users\12094\anaconda3\lib\site-packages (from httpx->python-fasthtml>=0.12.34->fastprogress>=1.0.0->intake-esm) (1.0.9)
Collecting cattrs>=22.2 (from requests-cache->pydap!=3.5.5->intake-esm)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache->pydap!=3.5.5->intake-esm)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting legacy-cgi>=2.6 (from Webob->pydap!=3.5.5->intake-esm)
  Downloading legacy_cgi-2.6.4-py3-none-any.whl.metadata (2.3 kB)
Downloading intake_esm-2025.12.12-py3-none-any.whl (35 kB)
Downloading polars-1.32.3-cp39-abi3-win_amd64.whl (38.0 MB)
   ---------------------------------------- 0.0/38.0 MB ? eta -:--:--
    --------------------------------------- 0.5/38.0 MB 3.5 MB/s eta 0:00:11
   - -------------------------------------- 1.6/38.0 MB 4.6 MB/s eta 0:00:08
   -- ------------------------------------- 2.4/38.0 MB 3.9 MB/s eta 0:00:10
   --- ------------------------------------ 3.1/38.0 MB 4.1 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/38.0 MB 4.1 MB/s eta 0:00:09
   ----- ---------------------------------- 5.0/38.0 MB 4.1 MB/s eta 0:00:09
   ------ --------------------------------- 6.0/38.0 MB 4.2 MB/s eta 0:00:08
   ------- -------------------------------- 7.1/38.0 MB 4.3 MB/s eta 0:00:08
   -------- ------------------------------- 8.4/38.0 MB 4.5 MB/s eta 0:00:07
   --------- ------------------------------ 9.4/38.0 MB 4.6 MB/s eta 0:00:07
   ---------- ----------------------------- 10.2/38.0 MB 4.5 MB/s eta 0:00:07
   ----------- ---------------------------- 10.7/38.0 MB 4.4 MB/s eta 0:00:07
   ------------ --------------------------- 11.5/38.0 MB 4.3 MB/s eta 0:00:07
   ------------ --------------------------- 12.3/38.0 MB 4.3 MB/s eta 0:00:07
   -------------- ------------------------- 13.6/38.0 MB 4.4 MB/s eta 0:00:06
   --------------- ------------------------ 15.2/38.0 MB 4.6 MB/s eta 0:00:05
   ----------------- ---------------------- 16.8/38.0 MB 4.8 MB/s eta 0:00:05
   ------------------ --------------------- 17.8/38.0 MB 4.8 MB/s eta 0:00:05
   ------------------- -------------------- 18.9/38.0 MB 4.8 MB/s eta 0:00:04
   --------------------- ------------------ 20.2/38.0 MB 4.9 MB/s eta 0:00:04
   ---------------------- ----------------- 21.5/38.0 MB 5.0 MB/s eta 0:00:04
   ----------------------- ---------------- 22.8/38.0 MB 5.0 MB/s eta 0:00:04
   ------------------------- -------------- 24.1/38.0 MB 5.1 MB/s eta 0:00:03
   ------------------------- -------------- 24.1/38.0 MB 5.1 MB/s eta 0:00:03
   ------------------------- -------------- 24.6/38.0 MB 4.8 MB/s eta 0:00:03
   -------------------------- ------------- 25.2/38.0 MB 4.7 MB/s eta 0:00:03
   ---------------------------- ----------- 26.7/38.0 MB 4.8 MB/s eta 0:00:03
   ------------------------------ --------- 28.8/38.0 MB 5.0 MB/s eta 0:00:02
   -------------------------------- ------- 31.2/38.0 MB 5.2 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/38.0 MB 5.4 MB/s eta 0:00:01
   -------------------------------------- - 36.2/38.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 38.0/38.0 MB 5.6 MB/s eta 0:00:00
Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl (21.3 MB)
   ---------------------------------------- 0.0/21.3 MB ? eta -:--:--
   --- ------------------------------------ 2.1/21.3 MB 10.3 MB/s eta 0:00:02
   -------- ------------------------------- 4.7/21.3 MB 11.8 MB/s eta 0:00:02

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2025.3.2 requires fsspec==2025.3.2.*, but you have fsspec 2026.3.0 which is incompatible.

In [15]:
import pandas as pd
import numpy as np
import xarray as xr
import gcsfs

fs = gcsfs.GCSFileSystem(token="anon")

df_cat = pd.read_csv(
    "https://cmip6.storage.googleapis.com/pangeo-cmip6.csv"
)

cities = {
    "Miami FL": (25.77, -80.19),
    "New Orleans LA": (29.95, -90.07),
    "Norfolk VA": (36.85, -76.29),
    "New York NY": (40.71, -74.01),
    "Atlantic City NJ": (39.36, -74.43),
    "Charleston SC": (32.78, -79.93),
    "Tampa FL": (27.95, -82.46),
    "Galveston TX": (29.30, -94.79),
    "Honolulu HI": (21.31, -157.86),
    "Seattle WA": (47.61, -122.33),
    "Boston MA": (42.36, -71.06),
    "San Francisco CA": (37.77, -122.42),
}

def get_lat_lon_names(ds):
    lat_name = next(name for name in ["lat", "latitude", "nav_lat"] if name in ds)
    lon_name = next(name for name in ["lon", "longitude", "nav_lon"] if name in ds)
    return lat_name, lon_name


def nearest_valid_ocean_timeseries(ds, data_array, city_lat, city_lon):
    lat_name, lon_name = get_lat_lon_names(ds)

    lats = ds[lat_name]
    lons = ds[lon_name]

    if float(lons.max()) > 180 and city_lon < 0:
        city_lon += 360

    # Use first time slice to find valid ocean cells
    first_slice = data_array.isel(time=0)
    valid_mask = np.isfinite(first_slice)

    dist = np.sqrt((lats - city_lat) ** 2 + (lons - city_lon) ** 2)

    # Only allow valid ocean cells
    dist = dist.where(valid_mask)

    y_dim, x_dim = lats.dims

    flat_index = int(np.nanargmin(dist.values))
    y_idx, x_idx = np.unravel_index(flat_index, dist.shape)

    return data_array.isel({y_dim: y_idx, x_dim: x_idx})


hist_subset = (
    df_cat.query(
        "variable_id == 'zos' & experiment_id == 'historical' & table_id == 'Omon'"
    )
    .drop_duplicates("source_id")
)

records = []

for _, row in hist_subset.head(10).iterrows():
    try:
        print("Loading", row.source_id)

        ds = xr.open_zarr(
            fs.get_mapper(row.zstore),
            consolidated=True
        )

        annual = (
            ds["zos"]
            .sel(time=slice("1850", "2014"))
            .resample(time="1YE")
            .mean()
        )

        for city, (lat, lon) in cities.items():
            ts = nearest_valid_ocean_timeseries(ds, annual, lat, lon).values
            print(city, np.isnan(ts).sum(), "missing out of", len(ts))
            print(ts[:5])
            for yr_idx, yr in enumerate(range(1850, 2015)):
                records.append({
                    "city": city,
                    "year": yr,
                    "segment": "historical_cmip6",
                    "scenario": "historical",
                    "model": row.source_id,
                    "dynamic_slr_cm": round(float(ts[yr_idx]), 2),
                })

    except Exception as e:
        print(f"Skipped {row.source_id}: {e}")
        continue

historical_df = pd.DataFrame(records)
historical_df.to_csv("data/historical_city_sea_level.csv", index=False)

historical_df.head()

Loading GFDL-ESM4
Miami FL 0 missing out of 165
[-0.23162723 -0.24209867 -0.2355633  -0.22925788 -0.2522898 ]
New Orleans LA 0 missing out of 165
[-0.16535619 -0.17288889 -0.1806159  -0.14503533 -0.16027786]
Norfolk VA 0 missing out of 165
[-0.668608  -0.7008651 -0.6744428 -0.6688878 -0.6592191]
New York NY 0 missing out of 165
[-0.68819046 -0.7147339  -0.6893373  -0.7059328  -0.6810608 ]
Atlantic City NJ 0 missing out of 165
[-0.6948169  -0.7256658  -0.69465995 -0.70711875 -0.68684393]
Charleston SC 0 missing out of 165
[-0.5143228  -0.5185407  -0.5319101  -0.4799812  -0.49064216]
Tampa FL 0 missing out of 165
[-0.22796404 -0.24864316 -0.23824877 -0.21719174 -0.24413775]
Galveston TX 0 missing out of 165
[-0.21370476 -0.21721707 -0.22688083 -0.1807652  -0.2094237 ]
Honolulu HI 0 missing out of 165
[0.5485115  0.5040565  0.4836751  0.50900817 0.55059266]
Seattle WA 0 missing out of 165
[0.24902199 0.24460691 0.27238184 0.25976714 0.27341172]
Boston MA 0 missing out of 165
[-0.63214433 -0.6623418  -0.6529489  -0.66668296 -0.6254894 ]
San Francisco CA 0 missing out of 165
[0.12292167 0.1349331  0.13982387 0.15323658 0.15266873]
Loading GFDL-CM4
Miami FL 0 missing out of 165
[-0.2506626  -0.25017548 -0.2595234  -0.24063493 -0.23012304]
New Orleans LA 0 missing out of 165
[-0.14398687 -0.1546185  -0.13769206 -0.13559571 -0.11635546]
Norfolk VA 0 missing out of 165
[-0.5282853  -0.49926582 -0.5410223  -0.5109665  -0.51253   ]
New York NY 0 missing out of 165
[-0.53940547 -0.51546603 -0.5652364  -0.5254293  -0.52588654]
Atlantic City NJ 0 missing out of 165
[-0.53950423 -0.5154846  -0.56237364 -0.5250979  -0.52606994]
Charleston SC 0 missing out of 165
[-0.49425635 -0.4786078  -0.4778012  -0.44509497 -0.45040655]
Tampa FL 0 missing out of 165
[-0.25508937 -0.25873706 -0.26010674 -0.26556283 -0.2393351 ]
Galveston TX 0 missing out of 165
[-0.17448449 -0.2062151  -0.17363524 -0.17992942 -0.16606216]
Honolulu HI 0 missing out of 165
[0.54509366 0.49943224 0.47719488 0.46671283 0.4514731 ]
Seattle WA 0 missing out of 165
[0.24505974 0.27376738 0.23871636 0.26121098 0.24401885]
Boston MA 0 missing out of 165
[-0.5275805  -0.5118403  -0.54323596 -0.5188821  -0.51856434]
San Francisco CA 0 missing out of 165
[0.12078876 0.15491183 0.14018244 0.13798988 0.14281566]
Loading IPSL-CM6A-LR
Miami FL 0 missing out of 165
[ 0.00076137  0.00411172 -0.01287402 -0.00188268 -0.0057414 ]
New Orleans LA 0 missing out of 165
[-0.00920961  0.00812166 -0.02190602 -0.02565907 -0.02439597]
Norfolk VA 0 missing out of 165
[-0.51013124 -0.4678376  -0.5375795  -0.4923834  -0.5036251 ]
New York NY 0 missing out of 165
[-0.6231547 -0.5187081 -0.6059086 -0.5380528 -0.5682938]
Atlantic City NJ 0 missing out of 165
[-0.59807616 -0.5218989  -0.6070464  -0.5480762  -0.56830263]
Charleston SC 0 missing out of 165
[-0.3986579  -0.38281128 -0.43531552 -0.40067208 -0.4068319 ]
Tampa FL 0 missing out of 165
[-0.00277299  0.0009056  -0.01310157 -0.01540072 -0.01400782]
Galveston TX 0 missing out of 165
[-0.01487005  0.00906337 -0.03118809 -0.03006045 -0.02752319]
Honolulu HI 0 missing out of 165
[0.56785816 0.5827632  0.5753505  0.61336476 0.5686206 ]
Seattle WA 0 missing out of 165
[0.11691456 0.16653945 0.1488104  0.14197873 0.15526654]
Boston MA 0 missing out of 165
[-0.5383163  -0.45827064 -0.52476424 -0.46119225 -0.5011604 ]
San Francisco CA 0 missing out of 165
[0.14364235 0.135309   0.10533067 0.12234768 0.16271067]
Loading GISS-E2-1-G
Skipped GISS-E2-1-G: not enough values to unpack (expected 2, got 1)
Loading CNRM-CM6-1
Miami FL 0 missing out of 165
[0.0353837  0.01823109 0.00974756 0.01168484 0.01351703]
New Orleans LA 0 missing out of 165
[0.07716141 0.07954047 0.09101766 0.04332155 0.08499561]
Norfolk VA 0 missing out of 165
[-0.5336284  -0.5576063  -0.57183284 -0.55631953 -0.5604679 ]
New York NY 0 missing out of 165
[-0.5535299 -0.5867999 -0.6058467 -0.5859012 -0.5838785]
Atlantic City NJ 0 missing out of 165
[-0.5645799  -0.5946438  -0.6194203  -0.59487796 -0.5955284 ]
Charleston SC 0 missing out of 165
[-0.4573379  -0.4644033  -0.4716698  -0.4567481  -0.46354663]
Tampa FL 0 missing out of 165
[ 0.02182417  0.00977691 -0.00458118 -0.01023729  0.00473419]
Galveston TX 0 missing out of 165
[0.0475038  0.04622905 0.07034879 0.01603672 0.05573054]
Honolulu HI 0 missing out of 165
[0.44779357 0.49804768 0.48736277 0.45514753 0.47564897]
Seattle WA 0 missing out of 165
[0.1412676  0.11974481 0.10980145 0.12670475 0.16698992]
Boston MA 0 missing out of 165
[-0.528709   -0.55745906 -0.56931645 -0.56562215 -0.5551663 ]
San Francisco CA 0 missing out of 165
[0.10653865 0.07235409 0.10083854 0.10860047 0.08048695]
Loading CNRM-ESM2-1
Miami FL 0 missing out of 165
[-0.02701193 -0.03245122 -0.01333608 -0.03152721 -0.02277697]
New Orleans LA 0 missing out of 165
[-0.01255602  0.03559714  0.01823474 -0.00815269  0.02790797]
Norfolk VA 0 missing out of 165
[-0.583592   -0.58185095 -0.5862852  -0.5867947  -0.5715696 ]
New York NY 0 missing out of 165
[-0.6702351  -0.67170566 -0.66168886 -0.6155965  -0.59730464]
Atlantic City NJ 0 missing out of 165
[-0.66081065 -0.6588784  -0.65833336 -0.631446   -0.60304385]
Charleston SC 0 missing out of 165
[-0.4680699  -0.4668902  -0.47659317 -0.49119866 -0.47121432]
Tampa FL 0 missing out of 165
[-0.05505531 -0.04776901 -0.02792895 -0.05227177 -0.0293825 ]
Galveston TX 0 missing out of 165
[-0.04354066  0.00032955 -0.008375   -0.02806126 -0.01530566]
Honolulu HI 0 missing out of 165
[0.4466302  0.40033725 0.5054372  0.4646434  0.46808147]
Seattle WA 0 missing out of 165
[0.12466744 0.13844047 0.14093192 0.10736763 0.10846069]
Boston MA 0 missing out of 165
[-0.6443443  -0.645431   -0.6255411  -0.5823418  -0.56785595]
San Francisco CA 0 missing out of 165
[0.07990982 0.10920932 0.09755957 0.08877036 0.06335714]
Loading MIROC6
Miami FL 0 missing out of 165
[ 0.02748937 -0.01121593  0.01837205  0.03684271  0.03614797]
New Orleans LA 0 missing out of 165
[ 0.01815707 -0.03105111  0.00277314  0.0114023   0.0121529 ]
Norfolk VA 0 missing out of 165
[-0.50322336 -0.5055587  -0.4995472  -0.5056853  -0.49507308]
New York NY 0 missing out of 165
[-0.4817358  -0.5057822  -0.51505035 -0.5359997  -0.53188735]
Atlantic City NJ 0 missing out of 165
[-0.5326166  -0.54803914 -0.54536736 -0.556207   -0.54759717]
Charleston SC 0 missing out of 165
[-0.20579155 -0.24111731 -0.20743734 -0.18264484 -0.16835976]
Tampa FL 0 missing out of 165
[ 0.00441665 -0.04444288 -0.00608217  0.01756087  0.01445313]
Galveston TX 0 missing out of 165
[-0.0034706  -0.04821742 -0.00408834 -0.00376466  0.01025192]
Honolulu HI 0 missing out of 165
[0.6066262  0.62223274 0.6143078  0.6019426  0.59700793]
Seattle WA 0 missing out of 165
[0.1528066  0.20969874 0.23648477 0.20929353 0.21126531]
Boston MA 0 missing out of 165
[-0.37774733 -0.40605855 -0.39785996 -0.40121582 -0.3913463 ]
San Francisco CA 0 missing out of 165
[0.17235766 0.2000383  0.22393155 0.21270484 0.18455458]
Loading AWI-CM-1-1-MR
Skipped AWI-CM-1-1-MR: not enough values to unpack (expected 2, got 1)
Loading CESM2
Skipped CESM2: not enough values to unpack (expected 2, got 1)
Loading SAM0-UNICON
Miami FL 0 missing out of 165
[-0.33014688 -0.34704232 -0.3522296  -0.34357694 -0.35307786]
New Orleans LA 0 missing out of 165
[-0.3076961  -0.30976218 -0.33749318 -0.31524143 -0.32472327]
Norfolk VA 0 missing out of 165
[-0.91600746 -0.955034   -0.94008833 -0.9350457  -0.93507856]
New York NY 0 missing out of 165
[-0.9614746  -0.99211097 -0.97260475 -0.9643485  -0.9833834 ]
Atlantic City NJ 0 missing out of 165
[-0.914829   -0.9371578  -0.92386025 -0.9176033  -0.93082523]
Charleston SC 0 missing out of 165
[-0.41268322 -0.4479444  -0.45007777 -0.4421357  -0.43168223]
Tampa FL 0 missing out of 165
[-0.2840719  -0.29198202 -0.31625608 -0.2935851  -0.30281243]
Galveston TX 0 missing out of 165
[-0.29644498 -0.29981112 -0.3335218  -0.30372322 -0.30962095]
Honolulu HI 0 missing out of 165
[0.7905826  0.75224763 0.7649908  0.78784055 0.80603474]
Seattle WA 0 missing out of 165
[0.14385791 0.15093696 0.20406127 0.19059022 0.22099811]
Boston MA 0 missing out of 165
[-1.0263671 -1.0600699 -1.0452427 -1.0327842 -1.0591835]
San Francisco CA 0 missing out of 165
[0.10905588 0.1240626  0.1804313  0.17990963 0.19821753]

       city  year           segment    scenario      model  dynamic_slr_cm
0  Miami FL  1850  historical_cmip6  historical  GFDL-ESM4           -0.23
1  Miami FL  1851  historical_cmip6  historical  GFDL-ESM4           -0.24
2  Miami FL  1852  historical_cmip6  historical  GFDL-ESM4           -0.24
3  Miami FL  1853  historical_cmip6  historical  GFDL-ESM4           -0.23
4  Miami FL  1854  historical_cmip6  historical  GFDL-ESM4           -0.25

In [16]:
scenarios = ['ssp126', 'ssp245', 'ssp370', 'ssp585']

future_records = []

for scenario in scenarios:

    print(f"\n=== Processing {scenario} ===")

    future_subset = (
        df_cat.query(
            f"variable_id == 'zos' & "
            f"experiment_id == '{scenario}' & "
            "table_id == 'Omon'"
        )
        .drop_duplicates("source_id")
    )

    for _, row in future_subset.head(10).iterrows():

        try:
            print(f"Loading {row.source_id}")

            ds = xr.open_zarr(
                fs.get_mapper(row.zstore),
                consolidated=True
            )

            annual = (
                ds["zos"]
                .sel(time=slice("2015", "2100"))
                .resample(time="1YE")
                .mean()
            )

            for city, (lat, lon) in cities.items():
                print(city, np.isnan(ts).sum(), "missing out of", len(ts))
                print(ts[:5])
                ts = nearest_valid_ocean_timeseries(
                    ds,
                    annual,
                    lat,
                    lon
                ).values

                for yr_idx, yr in enumerate(range(2015, 2101)):

                    future_records.append({
                        "city": city,
                        "year": yr,
                        "segment": "future_cmip6",
                        "scenario": scenario,
                        "model": row.source_id,
                        "dynamic_slr_cm": round(
                            float(ts[yr_idx]),
                            2
                        ),
                    })

        except Exception as e:
            print(f"Skipped {row.source_id}: {e}")
            continue

=== Processing ssp126 ===
Loading GFDL-ESM4
Miami FL 0 missing out of 165
[0.10905588 0.1240626  0.1804313  0.17990963 0.19821753]
New Orleans LA 0 missing out of 86
[-0.23893194 -0.21872927 -0.2089595  -0.22369814 -0.22949362]
Norfolk VA 0 missing out of 86
[-0.16283903 -0.13245998 -0.07772598 -0.11296517 -0.15784183]
New York NY 0 missing out of 86
[-0.6486004  -0.57721037 -0.5589343  -0.6509866  -0.6381387 ]
Atlantic City NJ 0 missing out of 86
[-0.6695662  -0.6231619  -0.6106015  -0.70456314 -0.69400406]
Charleston SC 0 missing out of 86
[-0.67473245 -0.6256977  -0.6101819  -0.6961689  -0.6845722 ]
Tampa FL 0 missing out of 86
[-0.49753186 -0.42634282 -0.4044524  -0.47487524 -0.4863131 ]
Galveston TX 0 missing out of 86
[-0.2216777  -0.21378358 -0.18496643 -0.2082743  -0.22706683]
Honolulu HI 0 missing out of 86
[-0.1990226  -0.17103706 -0.12401977 -0.14255069 -0.1950729 ]
Seattle WA 0 missing out of 86
[0.5310115  0.53764844 0.5278643  0.50370944 0.49339202]
Boston MA 0 missing out of 86
[0.20217918 0.26021412 0.2669656  0.21449812 0.23401849]
San Francisco CA 0 missing out of 86
[-0.6053885  -0.58979595 -0.57188827 -0.65101707 -0.64400357]
Loading AWI-CM-1-1-MR
Miami FL 0 missing out of 86
[0.07722831 0.11899546 0.1480643  0.09274057 0.11576156]
Skipped AWI-CM-1-1-MR: not enough values to unpack (expected 2, got 1)
Loading CNRM-CM6-1
Miami FL 0 missing out of 86
[0.07722831 0.11899546 0.1480643  0.09274057 0.11576156]
New Orleans LA 0 missing out of 86
[0.03454752 0.0502211  0.07372304 0.06782785 0.04485721]
Norfolk VA 0 missing out of 86
[0.11220517 0.15051466 0.14326157 0.13943961 0.09773979]
New York NY 0 missing out of 86
[-0.55302924 -0.5325745  -0.51754767 -0.47681722 -0.4915626 ]
Atlantic City NJ 0 missing out of 86
[-0.60861176 -0.5905003  -0.5787348  -0.5315283  -0.55389094]
Charleston SC 0 missing out of 86
[-0.61016345 -0.59273106 -0.583839   -0.53138393 -0.55866003]
Tampa FL 0 missing out of 86
[-0.4451495  -0.4181365  -0.41484198 -0.39041555 -0.38192323]
Galveston TX 0 missing out of 86
[0.03770713 0.05817493 0.08144568 0.06740292 0.03193712]
Honolulu HI 0 missing out of 86
[0.0814454  0.1369967  0.11029399 0.10932205 0.0695127 ]
Seattle WA 0 missing out of 86
[0.45891777 0.44941917 0.5061016  0.49639964 0.49257842]
Boston MA 0 missing out of 86
[0.19619314 0.13012396 0.147586   0.13147897 0.13840474]
San Francisco CA 0 missing out of 86
[-0.57526726 -0.55344063 -0.5448021  -0.50652665 -0.5298013 ]
Loading CNRM-ESM2-1
Miami FL 0 missing out of 86
[0.1112686  0.10142437 0.07262067 0.07508703 0.07500634]
New Orleans LA 0 missing out of 86
[-0.00312309 -0.01800356 -0.0134753   0.00553752  0.03007495]
Norfolk VA 0 missing out of 86
[0.03001478 0.02671978 0.05994834 0.08321647 0.06616565]
New York NY 0 missing out of 86
[-0.56704414 -0.5473416  -0.57341737 -0.5129382  -0.54779255]
Atlantic City NJ 0 missing out of 86
[-0.6327351  -0.5986632  -0.63134664 -0.59597224 -0.62433183]
Charleston SC 0 missing out of 86
[-0.6337003  -0.6041504  -0.63612396 -0.5858651  -0.615771  ]
Tampa FL 0 missing out of 86
[-0.45862165 -0.4494512  -0.46164414 -0.41968992 -0.45389548]
Galveston TX 0 missing out of 86
[-0.01938313 -0.03721465 -0.02033397  0.00298662  0.02724326]
Honolulu HI 0 missing out of 86
[-0.0042365  -0.00371044  0.04581125  0.04849193  0.02749143]
Seattle WA 0 missing out of 86
[0.49471232 0.4837145  0.47053722 0.44847587 0.4765245 ]
Boston MA 0 missing out of 86
[0.14524527 0.14889395 0.15725507 0.14992653 0.16317178]
San Francisco CA 0 missing out of 86
[-0.598967  -0.5630202 -0.6015837 -0.5749728 -0.5917064]
Loading IPSL-CM6A-LR
Miami FL 0 missing out of 86
[0.08361445 0.06636877 0.07709765 0.08232146 0.07959483]
New Orleans LA 0 missing out of 86
[0.01464346 0.01139611 0.00338447 0.01587364 0.02677654]
Norfolk VA 0 missing out of 86
[-0.00830038  0.00728918 -0.01909078 -0.00975473  0.00680013]
New York NY 0 missing out of 86
[-0.48007002 -0.47943345 -0.47841707 -0.48035607 -0.41165426]
Atlantic City NJ 0 missing out of 86
[-0.49225077 -0.4913437  -0.48521534 -0.5356304  -0.41832113]
Charleston SC 0 missing out of 86
[-0.5190879  -0.5113387  -0.50925905 -0.5460634  -0.43876076]
Tampa FL 0 missing out of 86
[-0.38235617 -0.3995081  -0.40330037 -0.37683952 -0.33296314]
Galveston TX 0 missing out of 86
[ 0.00259517 -0.00276799 -0.01512751 -0.00031061  0.01036072]
Honolulu HI 0 missing out of 86
[-0.01592814 -0.00066304 -0.02378394 -0.00972507  0.00565137]
Seattle WA 0 missing out of 86
[0.5714975  0.59859425 0.62662846 0.6043113  0.58061606]
Boston MA 0 missing out of 86
[0.13764292 0.15155916 0.10902432 0.05941339 0.14502496]
San Francisco CA 0 missing out of 86
[-0.42105877 -0.42039058 -0.41054693 -0.44442454 -0.36127028]
Loading BCC-CSM2-MR
Miami FL 0 missing out of 86
[0.10928421 0.12461001 0.0819962  0.10683095 0.16660053]
Skipped BCC-CSM2-MR: not enough values to unpack (expected 2, got 1)
Loading CanESM5-CanOE
Miami FL 0 missing out of 86
[0.10928421 0.12461001 0.0819962  0.10683095 0.16660053]
New Orleans LA 0 missing out of 86
[-0.09109477 -0.07926048 -0.07547928 -0.06207578 -0.08507308]
Norfolk VA 0 missing out of 86
[-0.03837387 -0.02807727 -0.01207028 -0.02342815 -0.05965156]
New York NY 0 missing out of 86
[-0.50641483 -0.47310427 -0.4929211  -0.47144374 -0.5074296 ]
Atlantic City NJ 0 missing out of 86
[-0.48594972 -0.47703657 -0.49241868 -0.48992398 -0.5134278 ]
Charleston SC 0 missing out of 86
[-0.5227886  -0.5074816  -0.52399784 -0.5119569  -0.5489936 ]
Tampa FL 0 missing out of 86
[-0.39103642 -0.36137494 -0.37953642 -0.34795606 -0.3916638 ]
Galveston TX 0 missing out of 86
[-0.0834564  -0.07060426 -0.0697243  -0.05764696 -0.08033802]
Honolulu HI 0 missing out of 86
[-0.02422064 -0.02205912 -0.01100026 -0.00911192 -0.04573819]
Seattle WA 0 missing out of 86
[0.52262187 0.52718836 0.5528347  0.5720534  0.5540523 ]
Boston MA 0 missing out of 86
[0.14429788 0.13356632 0.13889743 0.10060832 0.12595548]
San Francisco CA 0 missing out of 86
[-0.4349929  -0.4254682  -0.43166146 -0.43697128 -0.44044754]
Loading CanESM5
Miami FL 0 missing out of 86
[0.11704163 0.11529527 0.12252685 0.0840196  0.10905576]
New Orleans LA 0 missing out of 86
[-0.09716932 -0.0841918  -0.08642062 -0.08916096 -0.08027146]
Norfolk VA 0 missing out of 86
[-0.0625246  -0.05366465 -0.0182255  -0.07406288 -0.04375556]
New York NY 0 missing out of 86
[-0.5272983  -0.5231555  -0.51566094 -0.50134057 -0.4998541 ]
Atlantic City NJ 0 missing out of 86
[-0.5627112  -0.5641654  -0.57025456 -0.54868275 -0.5355534 ]
Charleston SC 0 missing out of 86
[-0.5803251  -0.57598156 -0.5732611  -0.55382204 -0.5548024 ]
Tampa FL 0 missing out of 86
[-0.40552917 -0.3887953  -0.38368973 -0.38368878 -0.36474264]
Galveston TX 0 missing out of 86
[-0.08892322 -0.07619523 -0.07505787 -0.08513781 -0.06995357]
Honolulu HI 0 missing out of 86
[-0.04961324 -0.03732537  0.00235021 -0.06527589 -0.01480207]
Seattle WA 0 missing out of 86
[0.53577596 0.54795855 0.54519635 0.5375948  0.57030535]
Boston MA 0 missing out of 86
[0.1580339  0.12510063 0.10963533 0.12019704 0.11101414]
San Francisco CA 0 missing out of 86
[-0.5010881  -0.50166595 -0.50406384 -0.4791834  -0.46483052]
Loading INM-CM4-8
Miami FL 0 missing out of 86
[0.14487948 0.10464073 0.08735915 0.09901623 0.08582065]
Skipped INM-CM4-8: not enough values to unpack (expected 2, got 1)
Loading INM-CM5-0
Miami FL 0 missing out of 86
[0.14487948 0.10464073 0.08735915 0.09901623 0.08582065]
Skipped INM-CM5-0: not enough values to unpack (expected 2, got 1)

=== Processing ssp245 ===
Loading GFDL-ESM4
Miami FL 0 missing out of 86
[0.14487948 0.10464073 0.08735915 0.09901623 0.08582065]
Skipped GFDL-ESM4: not enough values to unpack (expected 2, got 1)
Loading AWI-CM-1-1-MR
Miami FL 0 missing out of 86
[0.14487948 0.10464073 0.08735915 0.09901623 0.08582065]
Skipped AWI-CM-1-1-MR: not enough values to unpack (expected 2, got 1)
Loading IPSL-CM6A-LR
Miami FL 0 missing out of 86
[0.14487948 0.10464073 0.08735915 0.09901623 0.08582065]
New Orleans LA 0 missing out of 86
[0.03019138 0.04722384 0.03073605 0.01998731 0.03662879]
Norfolk VA 0 missing out of 86
[0.006956   0.04782921 0.02917943 0.02722804 0.05103436]
New York NY 0 missing out of 86
[-0.50685346 -0.45398536 -0.44868603 -0.4582754  -0.5006163 ]
Atlantic City NJ 0 missing out of 86
[-0.61840296 -0.53406143 -0.5011925  -0.4872843  -0.5947498 ]
Charleston SC 0 missing out of 86
[-0.5985255  -0.527987   -0.50795275 -0.50138813 -0.5849022 ]
Tampa FL 0 missing out of 86
[-0.38972035 -0.34045935 -0.35054228 -0.36875454 -0.38178715]
Galveston TX 0 missing out of 86
[0.01768833 0.04426995 0.01977597 0.00345564 0.03676341]
Honolulu HI 0 missing out of 86
[0.00080212 0.05382779 0.03522952 0.02717552 0.05123433]
Seattle WA 0 missing out of 86
[0.5885971  0.589822   0.59115416 0.6238914  0.5813202 ]
Boston MA 0 missing out of 86
[0.09081651 0.1145291  0.13680845 0.14109989 0.12714954]
San Francisco CA 0 missing out of 86
[-0.52574414 -0.45469975 -0.42266122 -0.41534725 -0.5062511 ]
Loading CNRM-CM6-1
Miami FL 0 missing out of 86
[0.08844027 0.09669178 0.13443363 0.13665542 0.14114858]
New Orleans LA 0 missing out of 86
[0.0239025  0.04240794 0.04854487 0.03217338 0.06338359]
Norfolk VA 0 missing out of 86
[0.10585149 0.13674296 0.07449084 0.1254767  0.14611776]
New York NY 0 missing out of 86
[-0.5704815  -0.5373223  -0.5200686  -0.51883096 -0.52712774]
Atlantic City NJ 0 missing out of 86
[-0.6392506 -0.5930238 -0.5547953 -0.5654194 -0.5959744]
Charleston SC 0 missing out of 86
[-0.6344842  -0.5954276  -0.56126255 -0.5776196  -0.5986753 ]
Tampa FL 0 missing out of 86
[-0.46100453 -0.4371812  -0.4407374  -0.41018787 -0.41835377]
Galveston TX 0 missing out of 86
[0.02240504 0.03920884 0.03360512 0.03629375 0.06753316]
Honolulu HI 0 missing out of 86
[0.08212578 0.11610753 0.03638874 0.09747437 0.11803594]
Seattle WA 0 missing out of 86
[0.45237818 0.48968485 0.47760406 0.46924147 0.47294462]
Boston MA 0 missing out of 86
[0.19552968 0.16877098 0.14658125 0.139123   0.12393864]
San Francisco CA 0 missing out of 86
[-0.6107313  -0.56147027 -0.53035885 -0.5265109  -0.5540104 ]
Loading CNRM-ESM2-1
Miami FL 0 missing out of 86
[0.10337307 0.07599957 0.0831316  0.10578334 0.09010584]
New Orleans LA 0 missing out of 86
[-0.03345243  0.01207963  0.0396269   0.03110711  0.02488142]
Norfolk VA 0 missing out of 86
[-0.01269866  0.10256342  0.1080213   0.11391395  0.06210926]
New York NY 0 missing out of 86
[-0.59050745 -0.5521899  -0.5418939  -0.5391098  -0.5209442 ]
Atlantic City NJ 0 missing out of 86
[-0.6447426  -0.6223165  -0.64323497 -0.6531984  -0.5869242 ]
Charleston SC 0 missing out of 86
[-0.652657   -0.62383    -0.6313821  -0.630383   -0.58157176]
Tampa FL 0 missing out of 86
[-0.48467827 -0.42853925 -0.4305304  -0.41631892 -0.42258516]
Galveston TX 0 missing out of 86
[-0.05700535  0.01873242  0.04181708  0.03893898  0.0091065 ]
Honolulu HI 0 missing out of 86
[-0.04960015  0.07935334  0.08578169  0.0890165   0.03600389]
Seattle WA 0 missing out of 86
[0.50376207 0.48771966 0.46757784 0.44580832 0.47754467]
Boston MA 0 missing out of 86
[0.10677845 0.08769364 0.12780468 0.13718963 0.16281158]
San Francisco CA 0 missing out of 86
[-0.5999472  -0.59491605 -0.6148179  -0.6277464  -0.5696017 ]
Loading CanESM5
Miami FL 0 missing out of 86
[0.06924856 0.05117501 0.05686301 0.08516753 0.10986813]
New Orleans LA 0 missing out of 86
[-0.07187255 -0.0648336  -0.0711375  -0.09587871 -0.07390246]
Norfolk VA 0 missing out of 86
[-0.03961186 -0.01954055 -0.02170517 -0.05987257 -0.02084957]
New York NY 0 missing out of 86
[-0.5047683  -0.46582004 -0.49106753 -0.49286616 -0.4771535 ]
Atlantic City NJ 0 missing out of 86
[-0.5130664  -0.44735578 -0.48146906 -0.45381188 -0.46730185]
Charleston SC 0 missing out of 86
[-0.54603153 -0.48313856 -0.5191841  -0.49436614 -0.5036821 ]
Tampa FL 0 missing out of 86
[-0.39134145 -0.35743654 -0.37025288 -0.39387274 -0.36734238]
Galveston TX 0 missing out of 86
[-0.06062154 -0.05798267 -0.06408778 -0.09567866 -0.0624331 ]
Honolulu HI 0 missing out of 86
[-2.6007170e-02 -1.0334045e-02 -1.1568268e-05 -5.3777423e-02
 -3.2408983e-03]
Seattle WA 0 missing out of 86
[0.5505471  0.54557157 0.53164214 0.5457385  0.57953304]
Boston MA 0 missing out of 86
[0.12683234 0.12739234 0.17027171 0.15869443 0.11444274]
San Francisco CA 0 missing out of 86
[-0.44238877 -0.39164582 -0.41596127 -0.40474543 -0.406559  ]
Loading BCC-CSM2-MR
Miami FL 0 missing out of 86
[0.10883193 0.13350864 0.1272598  0.12564136 0.08091792]
Skipped BCC-CSM2-MR: not enough values to unpack (expected 2, got 1)
Loading CanESM5-CanOE
Miami FL 0 missing out of 86
[0.10883193 0.13350864 0.1272598  0.12564136 0.08091792]
New Orleans LA 0 missing out of 86
[-0.09276908 -0.10843146 -0.08448301 -0.09530422 -0.09260955]
Norfolk VA 0 missing out of 86
[-0.05849277 -0.10079513 -0.05541551 -0.05354339 -0.07636862]
New York NY 0 missing out of 86
[-0.49495432 -0.5391242  -0.49305925 -0.49435523 -0.49098715]
Atlantic City NJ 0 missing out of 86
[-0.48106316 -0.5440305  -0.5315192  -0.4849737  -0.48184457]
Charleston SC 0 missing out of 86
[-0.5125674  -0.57845366 -0.5471669  -0.5209784  -0.5113194 ]
Tampa FL 0 missing out of 86
[-0.39426744 -0.42267585 -0.3695103  -0.3807558  -0.37613475]
Galveston TX 0 missing out of 86
[-0.08711942 -0.10432192 -0.07681817 -0.08917763 -0.08674084]
Honolulu HI 0 missing out of 86
[-0.05542282 -0.08803337 -0.04844487 -0.04479722 -0.05484192]
Seattle WA 0 missing out of 86
[0.5216747  0.5407915  0.5645042  0.5789351  0.54628754]
Boston MA 0 missing out of 86
[0.14578982 0.15136631 0.12734902 0.1668336  0.14747886]
San Francisco CA 0 missing out of 86
[-0.4294244  -0.4805062  -0.46467638 -0.42071593 -0.4267985 ]
Loading UKESM1-0-LL
Miami FL 0 missing out of 86
[0.12435189 0.12569736 0.11083903 0.14481781 0.13765684]
New Orleans LA 0 missing out of 86
[-0.15951236 -0.18974312 -0.17596595 -0.18161607 -0.18852068]
Norfolk VA 0 missing out of 86
[-0.10507197 -0.1574657  -0.14652437 -0.16274484 -0.16709958]
New York NY 0 missing out of 86
[-0.645832  -0.6647268 -0.6394389 -0.6774614 -0.6291599]
Atlantic City NJ 0 missing out of 86
[-0.61977583 -0.64969796 -0.6375249  -0.6873316  -0.6211476 ]
Charleston SC 0 missing out of 86
[-0.66302127 -0.67688566 -0.6638354  -0.7167401  -0.6462399 ]
Tampa FL 0 missing out of 86
[-0.5169726  -0.5559185  -0.52477795 -0.55714744 -0.54593056]
Galveston TX 0 missing out of 86
[-0.14508961 -0.18331468 -0.16814373 -0.16901118 -0.18307324]
Honolulu HI 0 missing out of 86
[-0.07660571 -0.12539344 -0.10907657 -0.14097995 -0.12839174]
Seattle WA 0 missing out of 86
[0.5529576  0.5587671  0.57595557 0.57642716 0.60132754]
Boston MA 0 missing out of 86
[0.07784813 0.10236958 0.09460982 0.1344116  0.1307043 ]
San Francisco CA 0 missing out of 86
[-0.5785608  -0.6134004  -0.60862964 -0.6468484  -0.5943321 ]
Loading INM-CM4-8
Miami FL 0 missing out of 86
[0.10094806 0.11384121 0.07398591 0.09532978 0.10543648]
Skipped INM-CM4-8: not enough values to unpack (expected 2, got 1)

=== Processing ssp370 ===
Loading GFDL-ESM4
Miami FL 0 missing out of 86
[0.10094806 0.11384121 0.07398591 0.09532978 0.10543648]
New Orleans LA 0 missing out of 86
[-0.24511944 -0.2371927  -0.22223265 -0.21453267 -0.24291293]
Norfolk VA 0 missing out of 86
[-0.17506303 -0.16702616 -0.14336975 -0.09687915 -0.1717487 ]
New York NY 0 missing out of 86
[-0.63731235 -0.61078256 -0.62753105 -0.6235421  -0.66838795]
Atlantic City NJ 0 missing out of 86
[-0.6618418  -0.6527898  -0.66556096 -0.6714297  -0.7112613 ]
Charleston SC 0 missing out of 86
[-0.6678052  -0.65232235 -0.6666222  -0.66528326 -0.70591384]
Tampa FL 0 missing out of 86
[-0.49548876 -0.44668067 -0.45673525 -0.4407486  -0.50148064]
Galveston TX 0 missing out of 86
[-0.23748337 -0.24144603 -0.22278036 -0.1952049  -0.22651517]
Honolulu HI 0 missing out of 86
[-0.20526516 -0.18000032 -0.19364087 -0.12947904 -0.2009847 ]
Seattle WA 0 missing out of 86
[0.54744834 0.5229549  0.48191032 0.5691539  0.5071638 ]
Boston MA 0 missing out of 86
[0.21401054 0.2404214  0.26924798 0.2549772  0.22837128]
San Francisco CA 0 missing out of 86
[-0.6085022  -0.60154957 -0.6156389  -0.62409467 -0.6433839 ]
Loading AWI-CM-1-1-MR
Miami FL 0 missing out of 86
[0.09155679 0.13365307 0.15704872 0.12125295 0.12831248]
Skipped AWI-CM-1-1-MR: not enough values to unpack (expected 2, got 1)
Loading IPSL-CM6A-LR
Miami FL 0 missing out of 86
[0.09155679 0.13365307 0.15704872 0.12125295 0.12831248]
New Orleans LA 0 missing out of 86
[0.02117578 0.01055412 0.01532089 0.05826968 0.02096831]
Norfolk VA 0 missing out of 86
[0.01662982 0.02919535 0.01264422 0.06971028 0.00675546]
New York NY 0 missing out of 86
[-0.47467303 -0.45284235 -0.47990444 -0.39567026 -0.483112  ]
Atlantic City NJ 0 missing out of 86
[-0.53330356 -0.47927853 -0.55756503 -0.471555   -0.5714515 ]
Charleston SC 0 missing out of 86
[-0.53524333 -0.49378896 -0.5483115  -0.4602839  -0.5597058 ]
Tampa FL 0 missing out of 86
[-0.37361825 -0.36146376 -0.39213908 -0.29626384 -0.38708496]
Galveston TX 0 missing out of 86
[0.01270611 0.00286462 0.00357115 0.05445855 0.01180293]
Honolulu HI 0 missing out of 86
[ 0.0149967   0.0376152   0.00667654  0.07124761 -0.01435512]
Seattle WA 0 missing out of 86
[0.61175734 0.66122293 0.6529255  0.5619626  0.590589  ]
Boston MA 0 missing out of 86
[0.13541876 0.17030863 0.11647559 0.18390219 0.16626471]
San Francisco CA 0 missing out of 86
[-0.44885707 -0.41596887 -0.4723183  -0.41616634 -0.4871069 ]
Loading CNRM-CM6-1
Miami FL 0 missing out of 86
[0.12971826 0.10453685 0.14431019 0.18234897 0.15355627]
New Orleans LA 0 missing out of 86
[0.02964968 0.02447455 0.02723493 0.04022015 0.04547786]
Norfolk VA 0 missing out of 86
[0.09733378 0.08945993 0.09200131 0.11404485 0.15734585]
New York NY 0 missing out of 86
[-0.5472759  -0.53909934 -0.5263432  -0.53798455 -0.4950682 ]
Atlantic City NJ 0 missing out of 86
[-0.6064438  -0.5905675  -0.55387217 -0.5884702  -0.55380785]
Charleston SC 0 missing out of 86
[-0.6087651  -0.59673154 -0.5653443  -0.59638065 -0.5561922 ]
Tampa FL 0 missing out of 86
[-0.4272771  -0.4350413  -0.43815026 -0.42879453 -0.4029816 ]
Galveston TX 0 missing out of 86
[0.01984905 0.01410856 0.02439687 0.04401987 0.06338941]
Honolulu HI 0 missing out of 86
[0.07833384 0.08044154 0.04318288 0.09310204 0.13606325]
Seattle WA 0 missing out of 86
[0.4557017  0.43355837 0.47541046 0.50264204 0.48333263]
Boston MA 0 missing out of 86
[0.17983562 0.13676877 0.14062865 0.16728778 0.1498407 ]
San Francisco CA 0 missing out of 86
[-0.5734091  -0.55364996 -0.5274036  -0.5534468  -0.52398723]
Loading CNRM-ESM2-1
Miami FL 0 missing out of 86
[0.08531243 0.08813157 0.08650648 0.07597957 0.08473483]
New Orleans LA 0 missing out of 86
[0.06952843 0.07270096 0.06534535 0.04707476 0.02864082]
Norfolk VA 0 missing out of 86
[0.12744354 0.14602022 0.1136857  0.07656402 0.0671311 ]
New York NY 0 missing out of 86
[-0.46719876 -0.46372652 -0.4566463  -0.46925268 -0.5014217 ]
Atlantic City NJ 0 missing out of 86
[-0.5532954  -0.5810387  -0.54097205 -0.5176574  -0.5731793 ]
Charleston SC 0 missing out of 86
[-0.54361194 -0.55757874 -0.53241235 -0.5256425  -0.5732456 ]
Tampa FL 0 missing out of 86
[-0.35727847 -0.34671572 -0.35796633 -0.3833994  -0.40020058]
Galveston TX 0 missing out of 86
[0.07026463 0.07843819 0.06304207 0.03339077 0.02163732]
Honolulu HI 0 missing out of 86
[0.09526259 0.12486557 0.07686412 0.03201392 0.04207607]
Seattle WA 0 missing out of 86
[0.45296443 0.44668376 0.45400038 0.47575805 0.5158846 ]
Boston MA 0 missing out of 86
[0.07295669 0.11973646 0.14219677 0.16817658 0.16657986]
San Francisco CA 0 missing out of 86
[-0.5205161  -0.5423498  -0.49398056 -0.47200873 -0.5250234 ]
Loading CanESM5
Miami FL 0 missing out of 86
[0.06328083 0.07510648 0.05848161 0.08281913 0.07953165]
New Orleans LA 0 missing out of 86
[-0.10281197 -0.09794211 -0.09710845 -0.0861573  -0.08579779]
Norfolk VA 0 missing out of 86

In [17]:
_future_df = pd.DataFrame(future_records)
_future_df.to_csv("data/future_city_sea_level.csv", index=False)

_future_df.head()

       city  year       segment scenario      model  dynamic_slr_cm
0  Miami FL  2015  future_cmip6   ssp126  GFDL-ESM4           -0.24
1  Miami FL  2016  future_cmip6   ssp126  GFDL-ESM4           -0.22
2  Miami FL  2017  future_cmip6   ssp126  GFDL-ESM4           -0.21
3  Miami FL  2018  future_cmip6   ssp126  GFDL-ESM4           -0.22
4  Miami FL  2019  future_cmip6   ssp126  GFDL-ESM4           -0.23

In [ ]:
combined_df = pd.concat([historical_df, _future_df], ignore_index=True)

       city  year           segment    scenario      model  dynamic_slr_cm
0  Miami FL  1850  historical_cmip6  historical  GFDL-ESM4           -0.23
1  Miami FL  1851  historical_cmip6  historical  GFDL-ESM4           -0.24
2  Miami FL  1852  historical_cmip6  historical  GFDL-ESM4           -0.24
3  Miami FL  1853  historical_cmip6  historical  GFDL-ESM4           -0.23
4  Miami FL  1854  historical_cmip6  historical  GFDL-ESM4           -0.25

In [21]:
city_coords = {
    "Miami FL": (25.77, -80.19),
    "New Orleans LA": (29.95, -90.07),
    "Norfolk VA": (36.85, -76.29),
    "New York NY": (40.71, -74.01),
    "Atlantic City NJ": (39.36, -74.43),
    "Charleston SC": (32.78, -79.93),
    "Tampa FL": (27.95, -82.46),
    "Galveston TX": (29.30, -94.79),
    "Honolulu HI": (21.31, -157.86),
    "Seattle WA": (47.61, -122.33),
    "Boston MA": (42.36, -71.06),
    "San Francisco CA": (37.77, -122.42),
}
combined_df["lat"] = combined_df["city"].map(
    lambda x: city_coords[x][0]
)

combined_df["lon"] = combined_df["city"].map(
    lambda x: city_coords[x][1]
)
combined_df.rename(columns={"dynamic_slr_cm": "zos_raw"}, inplace=True)
combined_df.to_csv("data/combined_city_sea_level.csv", index=False)